//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int commentid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> eventid { get; set; }
        public string comment1 { get; set; }
        public string Report { get; set; }
        public string username { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
