//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public int mapid { get; set; }
        public Nullable<int> eventid { get; set; }
        public string coorlat { get; set; }
        public string coorlong { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
