//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int reportId { get; set; }
        public int eventid { get; set; }
        public string report1 { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
